### ISSUE TITLE
[1.12.2] Crash with Chisels & Bits + Mekanism

### ISSUE THREAD

**Issue by ghost** [amadornes/MCMultiPart#102]
I placed bits on a wall and instantly crashed.

**Crash log:** https://pastebin.com/raw/nNfjEErb

After I placed a bit over a [Mekanism](https://minecraft.curseforge.com/projects/mekanism) cable, I couldn’t access the world anymore, so I had to restore to a backup since my world basically became corrupt.

**Minecraft version:** 1.12.2
**Modpack:** [All the Mods 3](https://minecraft.curseforge.com/projects/all-the-mods-3), v. 4.4
**Chisels & Bits version:** 14.9
**MCMultiPart version:** 2.3.3

****

AlgorithmX2/Chisels-and-Bits/issues/322
AlgorithmX2/Chisels-and-Bits/issues/310

**Comment by RacerDelux** [comment]
More info here: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310

**Comment by StarkRG** [comment]
I can confirm this issue: https://pastebin.com/2JByyfyr

**Comment by raoulvdberge** [comment]
This has been fixed with the chisel n bits workaround.

**Comment by electroCutie** [comment]
> This has been fixed with the chisel n bits workaround.

What is the workaround?
