### ISSUE TITLE
New API Questions

### ISSUE THREAD

**Issue by SonarSonic** [amadornes/MCMultiPart#115]
Hi There,
I'm the dev of https://minecraft.curseforge.com/projects/practical-logistics-2 which relies heavily on MCMultipart (thanks very much for all your work btw).

I'm currently porting to 1.12.2 and I'm planning to depend entirely on MCMultipart (as I did on 1.10.2) and not have it as a soft dependency.
However, having real trouble with getting multiparts to actually form, I have a block a which implements IMultipart and a tile which implement IMultipartTile and has the capability also, using ItemBlockMultipart to place it. They're bounding boxes do not cross, but they simply won't form a multipart container, are their additional methods I need to override?

I tried canPlacePartAt and canPlacePartOnSide, but if both of these return true the block is overwritten rather than combined, despite it being in a different PartSlot. Any pointers in the right direction will be hugely appreciated! Thanks!

**Comment by dblsaiko** [comment]
Try debugging it, I guess? (Start at ItemBlockMultipart#placePartAt)
Without your code there isn't anything to go off of. The parts overriding themselves does sound like they have the same IPartSlot, though

**Comment by SonarSonic** [comment]
Thank you that was exactly what I needed, I hadn't realised the getSlotForPlacement didn't pass the parts IBlockState from getStateForPlacement.

**Comment by dblsaiko** [comment]
No problem! :)
