### ISSUE TITLE
Crash with RefinedStorge and Mekanism

### ISSUE THREAD

**Issue by Janrupf** [amadornes/MCMultiPart#120]
Every time I place a cable from Mekanism or RefinedStorage in a already placed Multiblock structure (build with chisel and bits) it crashes with a Nullpointer.
After the crash the block is places like it should. (<- only Mekanism, RS behavior is below)

[Crashlog + a few more lines above it](https://pastebin.com/qS3eymKc)

EDIT: I don't know if this is related to RefinedStorage, but placing any bit on a block where a cable is generates an invisible bug block. (This is happening on a server)
`/testfor` outputs `tile.name.null`
This is only happening with RS cables, not with Mekanism cables/pipes/etc

**Comment by dblsaiko** [comment]
Does it still crash without WAILA? Looks like its selection tooltip renderer is causing it. Will look into it tomorrow, probably

**Comment by raoulvdberge** [comment]
This bug is for 1.11.2 btw. Would be helpful if the bugreporter stated that.

**Comment by dblsaiko** [comment]
It doesn't crash for me, but there is definitely some weird bugs (for example, [this](https://gist.github.com/therealfarfetchd/52a19e7917fd39cb9876eebdd0254033) error and a LOT of invisible blocks) in there that my changes in the 1.12 branch probably fixed. I'll see if I can port them to this branch, shouldn't be too difficult to do

**Comment by dblsaiko** [comment]
Fixed with #121.
