### ISSUE TITLE
Clicking with multiparts

### ISSUE THREAD

**Issue by adrwa** [amadornes/MCMultiPart#125]
When right clicking with a block that has had a stack wrapper applied, there are two issues

1. ~~If MCMP thinks the block can be placed, it'll place the block without asking the clicked block about onBlockActivated~~

2. Clicking with a multipart but cant be placed will trigger onBlockActivated, but if the activation is successful, there is no item animation for clicking

**Comment by dblsaiko** [comment]
Duplicate of #73 I guess?

**Comment by adrwa** [comment]
Whoops i didnt see that, number 2 isnt mentioned in that issue so only the first part is a duplicate as far as i can see
