### ISSUE TITLE
Crash with updating cable

### ISSUE THREAD

**Issue by Boingboingsplat** [amadornes/MCMultiPart#13]
I found a crash when connecting a CharSet redstone cable next to a block containing a redstone cable and a some Chisel&Bits bits.

![2016-01-29_23 59 34](https://cloud.githubusercontent.com/assets/7320818/12693800/da0d3014-c6e4-11e5-9c0a-011bc6167592.png)

The block contains the redstone cable and some pink wool bits. When I place a redstone cable on the currently highlighted block, it crashes with the following crash log: http://paste.ee/p/1sCvm

Upon reloading the world, everything is fine, with the cables placed and connected as expected. The crash also occurs if the wires are placed in the opposite order, with the bits already in place.

**Comment by amadornes** [comment]
This was fixed a few days ago when I added capability wrappers. I'll look into uploading a new build today :)
