### ISSUE TITLE
Crash after player broke a multipart with generous amounts of Charset wires

### ISSUE THREAD

**Issue by asiekierka** [amadornes/MCMultiPart#135]
https://paste.dimdev.org/wifacufesa.coffeescript

Is this my fault or not?

**Comment by dblsaiko** [comment]
Looks like MCMP's fault. Doesn't check if the hit block position is null/if a block is hit... [TESRMultipartContainer:41](https://github.com/amadornes/MCMultiPart/blob/1.12/src/main/java/mcmultipart/client/TESRMultipartContainer.java#L41)
