### ISSUE TITLE
[1.10.2] Crash when breaking Mekanism cables

### ISSUE THREAD

**Issue by xenorio** [amadornes/MCMultiPart#138]
Minecraft Version: 1.10.2
Mekanism: 9.2.3.97 (MekanismGenerators and MekanismTools are installed)
MCMultiPart: 1.4.0 Universal
Forge: 12.18.3.2511

Crash Report: [https://pastebin.com/kFQyS0nr](https://pastebin.com/kFQyS0nr)

When trying to break a Basic Universal Cable with any tool (Or hand), Minecraft crashes.

**Comment by dblsaiko** [comment]
MCMP 1.x is unsupported, it has not been worked on in close to 2 years now...

**Comment by xenorio** [comment]
@therealfarfetchd 

so where can i get a supported version then? on [CurseForge](https://minecraft.curseforge.com/projects/mcmultipart/files) the newest version that's made for 1.10.2 is 1.4.0 (I need it for 1.10.2 because i'm playing a specific modpack)

Even the GitHub releases only go up to 1.0.4

**Comment by dblsaiko** [comment]
There's no later versions for 1.10. Stacktrace mentions treecapitator, can you try removing that temporarily and see if it still occurs?

**Comment by tomelfring** [comment]
This is indeed an incompatability between Mekanism and Treecapacitator. Nothing to blame on MCMultiPart

**Comment by xenorio** [comment]
Removing Treecapitator solved the issue! Thanks for your help, guys!

Closing this now.
