### ISSUE TITLE
Refined Storage Cables

### ISSUE THREAD

**Issue by VULTRANOS** [amadornes/MCMultiPart#139]
What should i do? i can't place it
![image](https://user-images.githubusercontent.com/35412338/52326584-57885680-29d0-11e9-862a-b3a7061eb6f3.png)

**Comment by dblsaiko** [comment]
I have no idea what that block you're holding is. Maybe it doesn't have multipart support.

**Comment by VULTRANOS** [comment]
> I have no idea what that block you're holding is. Maybe it doesn't have multipart support.

It's weathered basalt bricks, from chisel.

Edit: I Can't place any other block too, it's happening with IC2 cables too

C&B: 14.30
MCMultiPart 2.5.3

**Comment by VULTRANOS** [comment]
It seems to work in 1.10.2 
![image](https://user-images.githubusercontent.com/35412338/52367020-348e8e80-2a32-11e9-84a6-f0d8d9b65c0f.png)

**Comment by dblsaiko** [comment]
Oh, so that's a block from Chisels & Bits. Should work, have you tested putting bits on other multiparts, or other multiparts in the same block as RS cables?

**Comment by dblsaiko** [comment]
Chisels & Bits supports multiparts, but neither Refined Storage (anymore) nor IC2 does.
