### ISSUE TITLE
In Material Hooks For Multiparts - C&B

### ISSUE THREAD

**Issue by AlgorithmX2** [amadornes/MCMultiPart#14]
Need Block.isAABBInsideMaterial / Block.isEntityInsideMaterial for Multiparts.

**Comment by amadornes** [comment]
I'm fairly busy today, so I'll look into it tomorrow :)

**Comment by AlgorithmX2** [comment]
![Image of Walrus](http://media.charlesleifer.com/blog/photos/walrus-lurker.jpg)

**Comment by amadornes** [comment]
Done! Will be in the next release! :)

**Comment by AlgorithmX2** [comment]
Tested, didn't have any issues :+1:
