### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity with Mekanism/MCMultipart (Universal Cable)

### ISSUE THREAD

**Issue by CausticLasagne** [amadornes/MCMultiPart#141]
This is a separate crash from https://github.com/amadornes/MCMultiPart/issues/59.

#### Issue description:
This issue is always reproducible using the specified mods/RR versions.
Teleported from Overworld to Spectre Dimension -> Game Crashed
Game Restarted
Teleported from Spectre Dimension to Overworld -> Game Crashed

#### Steps to reproduce:
1. Make RFTools Reciever, Sender and Dialer
2. Connect to power source using Mekanism Universal cable
3. Repeat above in spectre dimension
4. Teleport between dimensions

#### Version:
**Forge:** 12.18.3.2511
**Mekanism:** MEKANISM-1.10.2-9.2.4.103
**Mekanism:** MEKANISMGENERATORS-1.10.2-9.2.4.103
**Mekanism:** MEKANISMTOOLS-1.10.2-9.2.4.103
**RandomThings:** RANDOMTHINGS-MC1.10.2-3.7.7.1
**RFTOOLS:** RFTOOLS-1.1X-7.16
**MCMULTIPART:** MCMULTIPART-1.4.0
(You can also duplicate this on ATL Resonant Rise 4.3.0.5-rc 1.10.2)
**Other relevant version:** 
World type is creative custom superflat, crash may have been caused by server overload during world loading.
I've reported this bug to the creator of Mekanism who pointed me over here.

#### Crash Log:
https://pastebin.com/q0MkuTB6

**Comment by dblsaiko** [comment]
MCMultiPart 1.x is no longer supported.

**Comment by CausticLasagne** [comment]
Okay so do I just replace mcMultipart with the latest version? Will it still work with mekanism and all the other mods that depend on it?

**Comment by dblsaiko** [comment]
Well, 2.x is only for 1.11/1.12, so you'd have to update everything.
