### ISSUE TITLE
NPE: Rendering Block Entity

### ISSUE THREAD

**Issue by Dyonovan** [amadornes/MCMultiPart#15]
Crash: http://pastebin.com/k3aMbumg

All I can think of is maybe add a te != null check there as that's the only thing i can see it crashing on.

Then again, maybe its my block

**Comment by Dyonovan** [comment]
I've just also been reminded that we have been having issues with te's not being there after being broken. We have had to add NPE checks on te's in rending all over the place

**Comment by amadornes** [comment]
It looks to me like the raytrace result has a null block position, which should never happen... But this is modding, things that shouldn't happen happen all the time. I'll push a fix soon and hopefully that'll do it.
