### ISSUE TITLE
client crash on multiplayer server

### ISSUE THREAD

**Issue by winsrp** [amadornes/MCMultiPart#20]
`[20:53:05] [Client thread/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (Fluxed Redstone-1.3.0.31.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-E-full.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/4/16 8:53 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
    at mcmultipart.client.multipart.ModelMultipartContainer.func_177551_a(ModelMultipartContainer.java:49)
    at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:886)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:853)
    at ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:657)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:407)
    at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
    at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:180)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:101)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:261)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:130)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:66)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:52)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
    at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
    at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:88)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:287)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:78)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:38)
    at java.lang.Thread.run(Thread.java:745)

`

**Comment by winsrp** [comment]
## `A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mcmultipart.client.multipart.ModelMultipartContainer.func_177551_a(ModelMultipartContainer.java:49)
    at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:886)
    at ConnectedTextures.isNeighbour(ConnectedTextures.java:853)
    at ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:657)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:407)
    at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:234)
    at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:180)
    at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:101)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusionQuads(BlockModelRenderer.java:261)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelAmbientOcclusion(BlockModelRenderer.java:130)

-- Block model being tesselated --
Details:
    Block: neotech:ironTank
    Block location: World: (-214,65,148), Chunk: (at 10,4,4 in -14,9; contains blocks -224,0,144 to -209,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Using AO: true
Stacktrace:
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:66)
    at net.minecraft.client.renderer.BlockModelRenderer.func_178259_a(BlockModelRenderer.java:52)

-- Block being tesselated --
Details:
    Block type: ID #771 (tile.neotech:ironTank // com.dyonovan.neotech.common.blocks.storage.BlockTank)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-214,65,148), Chunk: (at 10,4,4 in -14,9; contains blocks -224,0,144 to -209,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:109)
    at gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:547)
    at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:88)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['winsrp'/16030, l='MpServer', x=-213.49, y=66.00, z=150.18]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -223.00,67.00,168.00 - World: (-223,67,168), Chunk: (at 1,4,8 in -14,10; contains blocks -224,0,160 to -209,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 839462 game time, 26983 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: true. Cheats: false
    Forced entities: 101 total; [EntityRabbit['Rabbit'/1, l='MpServer', x=-231.69, y=68.00, z=140.53], EntityZombie['Zombie'/15617, l='MpServer', x=-251.50, y=51.00, z=197.50], EntityFallenKnight['Fallen Knight'/15363, l='MpServer', x=-204.50, y=37.00, z=174.50], EntityBat['Bat'/14603, l='MpServer', x=-239.75, y=36.91, z=165.75], EntitySkeleton['Skeleton'/15115, l='MpServer', x=-234.50, y=42.00, z=207.50], EntityPlayerSP['winsrp'/16030, l='MpServer', x=-213.49, y=66.00, z=150.18], EntityCreeper['Creeper'/16140, l='MpServer', x=-236.50, y=41.00, z=212.50], EntityZombie['Zombie'/16145, l='MpServer', x=-248.50, y=19.00, z=188.50], EntityBat['Bat'/15634, l='MpServer', x=-238.22, y=53.10, z=190.44], EntitySquid['Squid'/15388, l='MpServer', x=-173.31, y=60.34, z=183.97], EntityRabbit['Rabbit'/30, l='MpServer', x=-293.91, y=70.00, z=132.91], EntityConcussionCreeper['Concussion Creeper'/15648, l='MpServer', x=-264.91, y=38.00, z=183.75], EntitySquid['Squid'/15138, l='MpServer', x=-176.53, y=60.00, z=185.13], EntitySkeleton['Skeleton'/15651, l='MpServer', x=-223.50, y=49.00, z=124.50], EntitySkeletonGun['Gun Skeleton'/13350, l='MpServer', x=-228.69, y=60.00, z=131.13], EntitySheep['Sheep'/39, l='MpServer', x=-253.78, y=68.00, z=77.81], EntitySkeleton['Skeleton'/15146, l='MpServer', x=-181.50, y=22.00, z=151.50], EntityPig['Pig'/43, l='MpServer', x=-266.22, y=61.78, z=84.69], EntityPig['Pig'/44, l='MpServer', x=-268.03, y=63.00, z=81.59], EntityPig['Pig'/46, l='MpServer', x=-260.06, y=70.00, z=142.03], EntityCreeper['Creeper'/15919, l='MpServer', x=-238.50, y=36.00, z=163.50], EntityZombie['Zombie'/15664, l='MpServer', x=-227.53, y=47.00, z=118.13], EntityOwl['Owl'/53, l='MpServer', x=-261.79, y=72.86, z=161.69], EntityOwl['Owl'/54, l='MpServer', x=-244.59, y=72.00, z=157.97], EntityItem['item.item.owlEgg'/14134, l='MpServer', x=-163.84, y=73.00, z=203.66], EntitySkeleton['Skeleton'/14911, l='MpServer', x=-200.50, y=36.00, z=177.50], EntityCreeper['Creeper'/8771, l='MpServer', x=-204.28, y=64.50, z=146.72], EntitySheep['Sheep'/69, l='MpServer', x=-255.25, y=68.00, z=78.34], EntityRabbit['Rabbit'/70, l='MpServer', x=-241.22, y=66.00, z=76.72], EntitySheep['Sheep'/71, l='MpServer', x=-244.25, y=63.00, z=71.53], EntityRabbit['Rabbit'/72, l='MpServer', x=-248.47, y=69.00, z=118.28], EntityOwl['Owl'/73, l='MpServer', x=-253.59, y=72.00, z=160.44], EntityRabbit['Rabbit'/76, l='MpServer', x=-246.69, y=71.00, z=166.34], EntityOwl['Owl'/77, l='MpServer', x=-262.56, y=71.00, z=159.50], EntityPig['Pig'/79, l='MpServer', x=-243.19, y=64.00, z=189.84], EntityRabbit['Rabbit'/83, l='MpServer', x=-252.91, y=64.00, z=201.13], EntityZombie['Zombie'/15448, l='MpServer', x=-218.50, y=32.00, z=175.50], EntityRabbit['Rabbit'/90, l='MpServer', x=-231.47, y=64.00, z=83.59], EntityRabbit['Rabbit'/91, l='MpServer', x=-240.03, y=68.00, z=86.03], EntitySquid['Squid'/15196, l='MpServer', x=-178.03, y=62.41, z=181.94], EntityBat['Bat'/6493, l='MpServer', x=-216.28, y=51.10, z=122.50], EntityRabbit['Rabbit'/95, l='MpServer', x=-242.16, y=66.00, z=186.28], EntitySquid['Squid'/15458, l='MpServer', x=-176.41, y=61.66, z=186.28], EntityCreeper['Creeper'/15459, l='MpServer', x=-250.50, y=37.00, z=163.50], EntityCreeper['Creeper'/13157, l='MpServer', x=-224.50, y=46.00, z=118.28], EntityZombie['Zombie'/14438, l='MpServer', x=-201.50, y=34.00, z=186.50], EntityCreeper['Creeper'/15211, l='MpServer', x=-195.69, y=35.00, z=177.47], EntityConcussionCreeper['Concussion Creeper'/14960, l='MpServer', x=-211.44, y=53.00, z=127.03], EntityBat['Bat'/114, l='MpServer', x=-213.75, y=52.10, z=125.59], EntityFallenKnight['Fallen Knight'/14451, l='MpServer', x=-176.50, y=22.00, z=149.50], EntityBat['Bat'/115, l='MpServer', x=-213.75, y=52.10, z=125.47], EntityBat['Bat'/116, l='MpServer', x=-214.56, y=52.10, z=122.25], EntityBat['Bat'/117, l='MpServer', x=-209.91, y=53.10, z=126.66], EntityBat['Bat'/118, l='MpServer', x=-216.47, y=51.10, z=125.53], EntityBat['Bat'/119, l='MpServer', x=-218.75, y=51.10, z=122.34], EntityBat['Bat'/120, l='MpServer', x=-216.41, y=51.10, z=122.69], EntityItem['item.item.arrow'/14975, l='MpServer', x=-208.16, y=64.00, z=150.75], EntityRabbit['Rabbit'/127, l='MpServer', x=-245.44, y=69.00, z=118.28], EntityConcussionCreeper['Concussion Creeper'/128, l='MpServer', x=-206.63, y=64.69, z=147.84], EntityCreeper['Creeper'/10627, l='MpServer', x=-195.38, y=65.00, z=181.06], EntityFallenKnight['Fallen Knight'/15491, l='MpServer', x=-210.50, y=23.00, z=201.50], EntitySquid['Squid'/15493, l='MpServer', x=-173.97, y=59.44, z=192.50], EntityRabbit['Rabbit'/135, l='MpServer', x=-196.59, y=63.00, z=197.41], EntityPig['Pig'/136, l='MpServer', x=-204.03, y=65.00, z=200.03], EntityBat['Bat'/10635, l='MpServer', x=-214.16, y=52.10, z=122.78], EntityZombie['Zombie'/15243, l='MpServer', x=-174.66, y=22.00, z=149.34], EntitySkeleton['Skeleton'/15756, l='MpServer', x=-190.50, y=13.00, z=192.50], EntityFallenKnight['Fallen Knight'/15760, l='MpServer', x=-237.19, y=44.00, z=179.59], EntitySpider['Spider'/15765, l='MpServer', x=-262.50, y=31.00, z=167.50], EntitySkeleton['Skeleton'/16024, l='MpServer', x=-196.50, y=32.00, z=187.50], EntitySkeleton['Skeleton'/15768, l='MpServer', x=-248.50, y=41.00, z=184.50], EntityZombie['Zombie'/16029, l='MpServer', x=-241.09, y=39.00, z=158.56], EntityOwl['Owl'/160, l='MpServer', x=-167.56, y=72.00, z=206.69], EntityOwl['Owl'/161, l='MpServer', x=-158.56, y=74.00, z=193.50], EntityOwl['Owl'/162, l='MpServer', x=-151.47, y=73.00, z=192.44], EntityOwl['Owl'/163, l='MpServer', x=-162.47, y=74.00, z=200.44], EntityItem['item.item.arrow'/13988, l='MpServer', x=-203.47, y=64.00, z=150.91], EntityRabbit['Rabbit'/173, l='MpServer', x=-144.28, y=74.00, z=131.09], EntityOwl['Owl'/174, l='MpServer', x=-166.50, y=72.00, z=207.78], EntityZombie['Zombie'/15535, l='MpServer', x=-263.50, y=38.00, z=183.50], EntityOwl['Owl'/175, l='MpServer', x=-150.50, y=70.00, z=189.44], EntityItem['item.item.owlEgg'/15538, l='MpServer', x=-158.03, y=74.00, z=193.81], EntitySquid['Squid'/15542, l='MpServer', x=-174.88, y=61.00, z=183.38], EntityZombie['Zombie'/15543, l='MpServer', x=-244.50, y=16.00, z=185.50], EntityCreeper['Creeper'/15801, l='MpServer', x=-224.50, y=40.00, z=217.50], EntityRabbit['Rabbit'/186, l='MpServer', x=-142.13, y=63.00, z=160.75], EntityBat['Bat'/15292, l='MpServer', x=-269.53, y=38.10, z=171.25], EntityCreeper['Creeper'/9406, l='MpServer', x=-207.75, y=64.69, z=148.84], EntityBat['Bat'/15808, l='MpServer', x=-272.75, y=30.94, z=162.41], EntityBat['Bat'/15810, l='MpServer', x=-202.16, y=32.56, z=188.47], EntityBat['Bat'/15305, l='MpServer', x=-206.25, y=35.10, z=176.75], EntityBat['Bat'/14027, l='MpServer', x=-223.50, y=47.10, z=118.25], EntityZombie['Zombie'/15314, l='MpServer', x=-237.09, y=52.00, z=190.53], EntityCreeper['Creeper'/13527, l='MpServer', x=-229.44, y=12.00, z=155.06], EntityCreeper['Creeper'/15325, l='MpServer', x=-269.50, y=40.00, z=169.50], EntityZombie['Zombie'/16107, l='MpServer', x=-248.50, y=41.00, z=185.50], EntityZombie['Zombie'/16114, l='MpServer', x=-252.50, y=19.00, z=184.50], EntityZombie['Zombie'/15348, l='MpServer', x=-265.50, y=35.00, z=187.50], EntitySkeleton['Skeleton'/15349, l='MpServer', x=-232.09, y=15.00, z=202.53], EntityCreeper['Creeper'/15608, l='MpServer', x=-238.50, y=45.00, z=216.50], EntityBat['Bat'/10747, l='MpServer', x=-230.25, y=62.10, z=140.75]]
    Retry entities: 0 total; []
    Server brand: fml,forge,sponge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:44)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by amadornes** [comment]
This was already fixed a couple of days ago. You can get the latest experimental version from maven if you want it to be fixed right away, but I'll be releasing a new public version today :)

**Comment by winsrp** [comment]
I'll wait on the public version tx.
