### ISSUE TITLE
UV in json

### ISSUE THREAD

**Issue by Alex-hawks** [amadornes/MCMultiPart#22]
when using a custom model that makes use of uv setting, MCMP ignores it.
![ss 2016-03-10 at 05 24 22](https://cloud.githubusercontent.com/assets/2046226/13665020/59ce11d6-e6e5-11e5-96ef-1ee89e6abad7.jpg)
the thing on the left is the multipart, and is meant to be a scaled down form of the thing on the right. it renders properly in the hand

**Comment by amadornes** [comment]
Solved on IRC. The uvlock property should be off :P
