### ISSUE TITLE
ISolidTopPart on parts that take the center slot not working

### ISSUE THREAD

**Issue by bdew** [amadornes/MCMultiPart#23]
There is a check [here](https://github.com/amadornes/MCMultiPart/blob/master/src/main/java/mcmultipart/multipart/MultipartContainer.java#L391) that makes only parts that take the top slot, or no slots work with that interface.

Is there any specific reason for that?

I have a centered column microblock in my covers mod that would be nice to be able to place a torch on, but it can't be in the top slot as covers should be placeable together with it.

**Comment by amadornes** [comment]
The main reason was that your part should be at the top of the block if it wants to make it solid, but this case also seems fair. I'll push a fix in a bit :)
