### ISSUE TITLE
[1.9] Crash when rendering model

### ISSUE THREAD

**Issue by pauljoda** [amadornes/MCMultiPart#25]
When rendering a model in a GUI, this crash occurs http://pastebin.com/fsHtnVwn

**Comment by pauljoda** [comment]
Was also able to have the same crash when trying to break the block, both instances occurred on a server

**Comment by Dyonovan** [comment]
This is whats appearing in the log

http://pastebin.com/j6AKyMaD

**Comment by bdew** [comment]
@pauljoda I don't think ModelMultipartContainer can render from an item. You need to map your items to your own part model.
