### ISSUE TITLE
[1.9] Blocks keep reappearing when broken after block update.

### ISSUE THREAD

**Issue by Dyonovan** [amadornes/MCMultiPart#26]
This is from the console 

http://pastebin.com/j6AKyMaD

**Comment by amadornes** [comment]
That's really weird... If you're running this in a dev environment with MCMP's deobfuscated version you may want to check your mappings and make sure they are the same ones as mine, though I'd recommend using forgegradle's obfuscated dependency system to work with any API.

**Comment by Dyonovan** [comment]
For some strange reason, by adding this code fixes the issue.

`override def getSelectedBoundingBoxDefault(state: IBlockState, world: World, pos: BlockPos): AxisAlignedBB = {
        state.getBoundingBox(world, pos)
    }`
