### ISSUE TITLE
MCMultiPart-1.1.0 crashes client on connect to SSP world 

### ISSUE THREAD

**Issue by kreezxil** [amadornes/MCMultiPart#28]
fml log: http://paste.ee/p/wvzQ3
crash report: http://paste.ee/p/ZCY3J

**Comment by shadowfacts** [comment]
Did you even read to what @amadornes [said on the last issue you posted](https://github.com/amadornes/MCMultiPart/issues/27#issuecomment-201941797)?

**Comment by kreezxil** [comment]
I read it, but I forgot that I read it.
Forge is not gonna revert their changes either, he should push his version.

**Comment by LlubNek** [comment]
I've got more of the same.
Crash report:  http://pastebin.com/2FKWGRVZ

If you've got a fix, please post it.  I don't think those changes are going away either, and we've already got other mods updating to the new Forge.  The ones that aren't are probably mostly waiting on MCMultiPart.

**Comment by amadornes** [comment]
It'll be on CurseForge later today
