### ISSUE TITLE
About TileMultipart(Container) being ITickable

### ISSUE THREAD

**Issue by fnuecke** [amadornes/MCMultiPart#30]
Unless I'm missing some magic happening behind the scenes (that has only been added in 1.9), every multipart tile entity is tickable. This is obviously suboptimal. In the case of covering (OC) cables, this will turn previously not ticking blocks into ticking ones, e.g.

Are there plans on avoiding this? If not, I propose having the tile entity be non-ticking and having a tick event handler that updates a list of all live ticking parts (alike the list of ticking tile entities managed by Minecraft). This would also do away with having to iterate all parts every tick and check if they are tickable. The other option might be an alternative non-ticking tile entity and swapping tile entities on demand, but that seems less robust to me.

**Comment by amadornes** [comment]
I've been meaning to do something like that for a while but I couldn't come up with a good way of doing it. I think I'm going to go with two variations of the TE: one that ticks and one that doesn't, to ensure compatibility with all mods. If anybody can come up with another way of doing it that won't be broken by things like frame mods, be sure to suggest it. I'll update this issue when I start working on it.

**Comment by MrTJP** [comment]
The way FMP is going to handle this is by mixing in the ITickable interface on the tile when an ITickable part is added. Completely possible in Java, just copy the tile data to a tickable version and silently replace.

**Comment by amadornes** [comment]
I was thinking about ways to do it a few days ago and I also thought about doing it like this. It'd probably be the safest option in terms of mod interaction and sticking to vanilla/Forge's standards. I'll look into implementing it today :)

**Comment by MrTJP** [comment]
When can I catch you on IRC? Have some questions...

**Comment by amadornes** [comment]
I'm on there all day at the weekend (usually from 9:00 to 00:00 CET) and on weekdays I join when I get home from school (from 15:00 to 23:30 most days). In terms of channels, since this is related to MCMP, #MCMultiPart would probably be best. That, or PMs.
Also, I just realised the name of the mod is going to cause trouble if you're updating CB's vanilla compat mod... :P
