### ISSUE TITLE
MultipartRegistry.registerPart taking String instead of ResourceLocation seems inconsistent

### ISSUE THREAD

**Issue by fnuecke** [amadornes/MCMultiPart#32]
Pretty much everything else has been switched out for ResourceLocations (in particular the part factories as well), so it seems somewhat inconsistent to have the registry take strings instead of ResourceLocations (i.e. `registerPart` and `registerPartFactory`). Since they get converted to ResourceLocations internally anyway, I'd suggest a compatibility overload still taking strings, but the main methods take a ResourceLocation instead?

Edit: and `PartPlacementWrapper.register`, too, I guess?

**Comment by amadornes** [comment]
That was kept like that because I did the port before Forge released its new registries. It's already fixed in the pull request I still haven't PRed :P

**Comment by dblsaiko** [comment]
Closing because this is an MCMP1 issue which has been outdated for a while. If this issue still occurs in MCMP2 (1.11+), please open a new issue.
