### ISSUE TITLE
[1.9.4] Crash during canAddPart check

### ISSUE THREAD

**Issue by rubensworks** [amadornes/MCMultiPart#33]
Calling `MultipartHelper#canAddPart` seems to crash due to a temporary tile trying to set a blockstate in a null-world.
I assume that this temporary tile should not be added as a listener to the part container, but you'll probably know better what's going on than I do ;-)

MCMP version 1.2.0_71
Crashlog: http://pastebin.com/UmiKiVTC

**Comment by amadornes** [comment]
Welp... "Fixes #33" should've closed it... I guess I'll do it manually
