### ISSUE TITLE
[1.9.4] Crash breaking Mekanism v9 cable with pickaxe

### ISSUE THREAD

**Issue by ruyanve** [amadornes/MCMultiPart#36]
Woops, I broke something!
Log: https://gist.github.com/ruyanve/1a5d3e8ce105b0f08b95548ac7836c98

ref ticket here: https://github.com/aidancbrady/Mekanism/issues/3369

**Comment by Xiaminou** [comment]
http://pastebin.com/cBMinvbU

**Comment by amadornes** [comment]
Yup... This is a thing... I'm still trying to figure it out :/

**Comment by Xiaminou** [comment]
Good to know, thanks.

**Comment by Eufranio** [comment]
Same here. https://github.com/aidancbrady/Mekanism/issues/3529

**Comment by amadornes** [comment]
The latest version of MCMultiPart shouldn't cause this anymore. Which one are you running?

**Comment by allanf181** [comment]
Same here.
http://pastebin.com/LB1EQP9i
MCMultiPart 1.2.0 Exp. 73

**Comment by amadornes** [comment]
Yeah... Get exp74 or the release version of 1.2.0, it's fixed there :)

**Comment by amadornes** [comment]
A fix that doesn't involve ignoring part hardnesses is now out. Still researching why it doesn't damage tools, but at least if you have a diamond pick it'll mine your multiparts faster than a wooden one, and faster than your hand :P
