### ISSUE TITLE
[Suggestion / Question] Left clicking blocks

### ISSUE THREAD

**Issue by SonarSonic** [amadornes/MCMultiPart#37]
Hey,

I'm developing a new mod around this framework which is fantastic to work with btw.
My only question is I don't see a way to prevent a Multiblock being destroyed when it is left clicked, 
I thought PartEvents would be cancelable, or if there was an interface which allows you to override this behaviour. Although I may have missed this.

Thank you for all your work :)

**Comment by amadornes** [comment]
Overriding if and how the block is broken can be done through the `harvest(PartMOP,EntityPlayer)` method in IMultipart. I'm not sure if that's what you were asking for, but it should take care of most use cases :)

**Comment by SonarSonic** [comment]
Perfect, thank you :)
