### ISSUE TITLE
Orphaned Parts & Update Packets

### ISSUE THREAD

**Issue by AlgorithmX2** [amadornes/MCMultiPart#46]
When Update packets are sent it seems that MCMP orphans any parts and just re-creates them from scratch, this isn't ideal, is there anyway to not do this? or at least have some trigger to tells a part that its been orphaned so it can clean itself up?

Code in question,
https://github.com/amadornes/MCMultiPart/blob/0f0f7c142546d606b9e9b26f06a6b29b9adeac61/src/main/java/mcmultipart/multipart/MultipartContainer.java#L436

**Comment by amadornes** [comment]
That's when it's read from NBT, though. Not when it's synced. A tile shouldn't be read from NBT more than once :P

**Comment by AlgorithmX2** [comment]
I submit the following evidence,

https://github.com/amadornes/MCMultiPart/blob/91bb73d532e78bb0a1f4b2fe8c257fe99652535f/src/main/java/mcmultipart/block/TileMultipartContainer.java#L255

**Comment by amadornes** [comment]
Dem evil packets... Working on a fix!
