### ISSUE TITLE
[MC 1.10 MCMultiPart 1.21] - Error messages in console

### ISSUE THREAD

**Issue by addrever** [amadornes/MCMultiPart#50]
Hello,

I am getting some error messages in the console.  The mod loads okay, but I wanted to bring it to your attention.
1. [06:41:56] [Client thread/ERROR]: Exception loading model for variant mcmultipart:multipart#ticking=false
   net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model mcmultipart:multipart#ticking=false with loader VariantLoader.INSTANCE, skipping
2. [06:41:56] [Client thread/ERROR]: Exception loading model for variant mcmultipart:multipart#ticking=true
   net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model mcmultipart:multipart#ticking=true with loader VariantLoader.INSTANCE, skipping

[Full Log](http://paste.ee/p/uYpAN)

**Comment by raoulvdberge** [comment]
This is probably fixed in the latest commit @amadornes?

**Comment by amadornes** [comment]
It is indeed. It's not a big deal, really, just some missing models that aren't even shown because I override them in-code.
