### ISSUE TITLE
Multiparts are converted to blocks before the parts are added/removed?

### ISSUE THREAD

**Issue by thecodewarrior** [amadornes/MCMultiPart#55]
I have an ItemMultiPart that places a scaffold part, the thing is that part can be immediately converted to a normal block. Whenever I place it on it's own it doesn't appear client-side until an update is caused nearby (no raytrace so it isn't just a rendering issue) and [this](http://pastebin.com/7EAxK3gG) error is fired.

A very similar issue is the following: If I have the same scaffold block and remove the last part sharing the block space it throws [this](http://pastebin.com/XVRhDEXy) error, though it seems to work ok. (Charset wires going around a corner don't update so I think the parts aren't being notified that they're removed)

This also brings up the fact that in the convertToBlock method I have to remove all the parts from the container. I would think setting the block would do that.

**Comment by amadornes** [comment]
Hmmm... Interesting... I'll look into it. There are a couple of things I needed to tweak in the internals and this was one of them, so good to know the fix is going to be worth it :)

**Comment by thecodewarrior** [comment]
Welp. Turns out adhering to the API is useful.

I wasn't returning true when I converted the block. Turns out the return value was used! Who woulda' thunk? Past me obviously didn't.
