### ISSUE TITLE
Crash when breaking a Mekanism's cable

### ISSUE THREAD

**Issue by quantumsheep** [amadornes/MCMultiPart#58]
This error happen when we try to break a Mekanism's cable. (I'm not alone with this glitch)

Minecraft version: 1.10.2
Forge version: 12.18.2.2118
MCMultiPart version: 1.3.0
Mekanism version: 9.2.0.292

Crash-Report: http://pastebin.com/rfGq1aG0

**Comment by quantumsheep** [comment]
Reported to Mekanism too: https://github.com/aidancbrady/Mekanism/issues/3943

**Comment by BrianEdmonds** [comment]
I ran into this as well. Tried upgrading Mekanism to 294 and Forge to 2121, but still crashes.

**Comment by RealGrep** [comment]
This only appeared in 1.3.0. Downgrading to 1.2.1 and I can break the cables just fine.

**Comment by quantumsheep** [comment]
I know it's work on 1.2.1 but for the next versions it need to be fixed

**Comment by P1st0lpr0** [comment]
Yes, it crashes for me , too.

**Comment by b0bst3r** [comment]
Yeah it's ok saying downgrade but there are mods which need 1.3.0 and I can't downgrade or bdews Covers mod crashes on startup.

**Comment by RealGrep** [comment]
I'm saying it was introduced in 1.3.0, so something that changed between 1.2.1 and 1.3.0 is involved, which might be helpful to ama. Of course, it can be useful to you if downgrading temporarily is an option, but I'm not offering this as a long term solution, nor was that the point of the information. :)

**Comment by NEXUS2345** [comment]
The issue appears to lie with Mekanism, not MCMP. MCMP introduced a change which Mekanism has not been updated to support. Mod pack developers should have picked up on this.

**Comment by b0bst3r** [comment]
Fixed in Mekanism Mekanism-1.10.2-9.2.1.295 using MCMultiPart-experimental-2.0.0_88-universal.

If you're wondering where to get 2.0.0_88 from don't it seems Mekanism or another mod is downloading it automatically.
