### ISSUE TITLE
Crash with mekanism energy cables with MCMultiPart

### ISSUE THREAD

**Issue by IchigoGames** [amadornes/MCMultiPart#59]
with MCMultiPart-1.3.0-universal crash mineing mek cable with MCMultiPart-1.2.1-universal no crash here is the crash report http://pastebin.com/FftDwSL2

**Comment by b0bst3r** [comment]
Fixed in Mekanism Mekanism-1.10.2-9.2.1.295 using MCMultiPart-experimental-2.0.0_88-universal

If you're wondering where to get 2.0.0_88 from don't it seems Mekanism or another mod is downloading it automatically.

**Comment by CausticLasagne** [comment]
@b0bst3r Hi. I am having this same issue with my game. Could you provide instructions to fix it please?
