### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by MvOGithub** [amadornes/MCMultiPart#60]
Hello Amadornes,

First of all, I hope I spelled your name correctly lol. Second of all, I have an idea, and would like to help you. I am absolutely in love with this, Super Circuit Maker and Chisels&Bits. But I would like to increase the amount of blocks in C&B. It's not your mod, but the mod-author said that basically everything compatible with this, would be compatible with C&B. Seeing as I can't mod yet, I would like it if there was an editor for MCMultiPart, similar to MCreator but not for making mods, just for adding some blocks. I know that that is a very hard task, so I would like to help you by making the editor itself. If you could help me by telling me how to add new blocks to MCMultiPart, I might be able to make an editor for this, that could make a mod that adds the new blocks desired, so that people can make their own mods. Long story short: A program that provides a GUI to make a mod that adds new blocks that are compatible with MCMultiPart, to make sure people like me can add tiny chests and rails :P.

Thanks for reading all this.

Sincerely,
Luuk, Team TaL Wolf

**Comment by amadornes** [comment]
Hmm... Okay, yeah... That's... a big request lol
I'd suggest asking the makers of MCreator to add MCMultiPart support instead of making a completely new tool from scratch that only works with MCMP. In my opinion that'd be the best option. It'd both improve an already existing tool and take much less effort because since the blocks it creates are fairly simple, they would surely be very easy to port to use MCMultiPart's API.

**Comment by MvOGithub** [comment]
Thanks, but before getting in contact with the mcreator devs, I would like to know how to change an mcreator block to an mcmultipart block, so I can test some stuff before hand.

**Comment by amadornes** [comment]
MCMultiPart doesn't use actual Blocks and TileEntities like vanilla does. It instead uses its own class called Multipart. You can extend it and implement your whole Block and TE in a single place. Once you've done that, you can register it in the MultipartRegistry and also register an item that extends ItemMultiPart to place it :)

**Comment by MvOGithub** [comment]
Thanks so much. I'm trying to get into modding, to make custom mods for my modpack, but I am a total noob at it. I'll check some source code etc, and I'll hopefully figure this out on my own. I will be trying it in a few hours, if it works, I'll close the issue, else I'll contact you :P. Good luck with your mods.

PS its freaking awesome that you are only like 17. Im 16 haha

**Comment by dblsaiko** [comment]
Closing because this has been inactive for a while.
