### ISSUE TITLE
Memory cells in general still seem to error when placed.

### ISSUE THREAD

**Issue by thecodewarrior** [amadornes/MCMultiPart#62]
https://gist.github.com/74c837a8998da1a54320a2e7f6f8bc16

(I'm trying to create a memory cell for a brainfuck computer's memory that can shift forward and backward)

**Comment by amadornes** [comment]
You.. probably want to report this in the SCM bugtracker (though I think it's been reported before) :P
https://github.com/amadornes/SCM-Localization-Issues

**Comment by thecodewarrior** [comment]
... crap. how did I...
