### ISSUE TITLE
[2.0] Missing getParts on IMultipartContainer api

### ISSUE THREAD

**Issue by MoreThanHidden** [amadornes/MCMultiPart#64]
Missing getParts on IMultipartContainer api

**Comment by MoreThanHidden** [comment]
Fixed in 28f591d633bc7b635f03a4cba5ec3915a088a933

**Comment by amadornes** [comment]
Oh, derp! Forgot to close it :P

**Comment by MoreThanHidden** [comment]
Thanks for that, Can stop using the Containers directly now :P
