### ISSUE TITLE
Mekanism not letting minecraft load.

### ISSUE THREAD

**Issue by killergrzjr** [amadornes/MCMultiPart#65]
Every time I try to run minecraft with Mekanism-1.10.2-9.2.1.295 it says "Mekanism DepLoader was unable to download required library MCMultiPart-experimental-2.0.0_88-universal.jar "

**Comment by wylderhoads1809** [comment]
I am also having this exact issue. I'll copy here what I posted on the curseforge page:

> I installed the latest version, and because of an issue with mekanism it won't intialize. Now I can't even find where the McMultipart files are stored. I deleted my mod folder and reinstalled every mod (except mcmultipart) and mekanism is still doing the same things. I can't find out how to remove your mod so I can actually play my world again.

**Comment by killergrzjr** [comment]
My friend helped me find a small work around, I'm trying it now to see if it works

**Comment by killergrzjr** [comment]
If it works i'll post instructions since nobody else on this whole forum seems to have an idea or they are too lazy to post to help us out

**Comment by raoulvdberge** [comment]
Go to Mekanism, they caused this issue.

**Comment by wylderhoads1809** [comment]
> If it works i'll post instructions since nobody else on this whole forum seems to have an idea or they are too lazy to post to help us out

Please let me know

**Comment by tomelfring** [comment]
The 1.10 branch of Mekanism removed the deploader. Sadly it's not provided in any official way. You can compile a working version yourself, or try the build at https://github.com/aidancbrady/Mekanism/issues/4119#issuecomment-270318661.
