### ISSUE TITLE
[MCMP2] Items with a stack wrapper registered ignore placement priorities

### ISSUE THREAD

**Issue by dblsaiko** [amadornes/MCMultiPart#72]
This is primarily visible when clicking on blocks with a GUI. The GUI will open and the multipart will be placed regardless if you're sneaking or not. What should happen is that if you're sneaking, it should only place the multipart and if you're not, it should open the GUI and not place the multipart.

**Comment by amadornes** [comment]
Should be resolved in the next build. I didn't have access to PlayerInteractEvent's new EnumActionResult return when I implemented wrapping.
