### ISSUE TITLE
[2.0.0] BlockColors are not used in rendering. 

### ISSUE THREAD

**Issue by darkevilmac** [amadornes/MCMultiPart#78]
I've recently taken to adding support for MCMP to my mod, I use BlockColors for different variations on my blocks but it seems that multiparts don't use these when rendering/creating models.

Not sure if this is a known issue but it's not documented on the issues page here from what I've seen, so it might as well be posted to use for tracking progress.

If anything about my explanation is unclear let me know and I'll elaborate.

**Comment by amadornes** [comment]
Yep. I knew of it, it just hadn't been implemented yet. Just added it :)
