### ISSUE TITLE
Crash upon Entering a Galacticraft Dimension

### ISSUE THREAD

**Issue by SirKillz** [amadornes/MCMultiPart#81]
Mc Multipart 1.4.0
Every time I launch into a Galacticraft Dimension or return from one my server crashes and give the following error.   
https://pastebin.com/Ww7GCKft

**Comment by tomelfring** [comment]
Duplicate of #71

**Comment by dblsaiko** [comment]
Closing because this is an MCMP1 issue which has been outdated for a while. If this issue still occurs in MCMP2 (1.11+), please open a new issue.
