### ISSUE TITLE
[1.11.2] NullPointerException / NoSuchElementException during ray tracing

### ISSUE THREAD

**Issue by Khepricus** [amadornes/MCMultiPart#83]
#### Issue description:
I encountered an exception using Chisels and Bits/Mekanism that triggers a crash in MCMultiPart during HWYLA's ray tracing

#### Steps to reproduce:
1. Hollow out a block using Chisels and Bits
2. Place a Mekanism Universal Cable inside the hollow block
3. Look at the multipart with HYWLA

#### Versions:
**Forge:** 13.20.0.2315 (also 13.20.0.2282)
**MCMultiPart:** 2.0.2 (also latest 1.11 branch)
**Mekanism:** 9.3.3
**Chisels and Bits:** 13.11
**HWYLA:** 1.8.15-B29_1.11

#### Crash log:
https://pastebin.com/457pHU3u

**Comment by Khepricus** [comment]
Also encountered this issue using a Refined Storage cable in place of a Mekanism cable. Have you had a chance to investigate this / review my pull request?

**Comment by amadornes** [comment]
Fixed by #97
