### ISSUE TITLE
getEffectiveSide()==Side.CLIENT will never be true

### ISSUE THREAD

**Issue by adrwa** [amadornes/MCMultiPart#86]
https://github.com/amadornes/MCMultiPart/blob/1.11/src/main/java/mcmultipart/multipart/PartInfo.java#L43

this code is always ran on the Server Thread when loading an existing world, getEffectiveSide will always return Server, what you want is just normal `getSide`

this causes my multipart blocks to never render.

**Comment by amadornes** [comment]
Huh... That's... Interesting O_o
I'll push a fix later today!
