### ISSUE TITLE
Rendering bug when placing microblocks

### ISSUE THREAD

**Issue by mbrockmeier** [amadornes/MCMultiPart#87]
This was posted to Chickenbones Repository. I think it will have a higher chance of getting fixed if I post it here: [Github Chickenbones Issue](https://github.com/Chicken-Bones/ForgeMultipart/issues/397)
[Imgur](http://i.imgur.com/08CWOu0.png)

In general it can occur if you place microblocks or if you have Dynamic lights enabled and walk by with a torch (It reacts to lighting changes).

Would be nice if you could rollback a fix to 1.10 version. (This happens with the 1.4 version on MC 1.10).

**Comment by amadornes** [comment]
Forge Microblocks (what you're using in that screenshot) uses Forge MultiPart, which isn't in any way related to MCMultiPart.
This is most likely a problem in their render pipeline but sadly I can't do anything about it, as none of my mods are even involved.
