### ISSUE TITLE
Crash with C&B (World not set?)

### ISSUE THREAD

**Issue by brisingraerowing** [amadornes/MCMultiPart#99]
[Crash Log](https://gist.github.com/BrisingrAerowing/84b649b5d713fbe067cee9c0027e378c)

I got this placing a bit into a multipart container to create a slab with a hole for an RS cable. Looking at the C&B code, it appears that the world the container is in is null.

**Comment by AlgorithmX2** [comment]
Linking C&B Issue, https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310

**Comment by asiekierka** [comment]
Does my latest PR fix this?

**Comment by AlgorithmX2** [comment]
I honestly think this was fixed by https://github.com/amadornes/MCMultiPart/commit/fad7549a615894ddb7439e10e8d197fd4072a303

so its probably no longer relevant.

**Comment by dblsaiko** [comment]
Does this still happen with the latest MCMultiPart version, @BrisingrAerowing ? I'm probably just going to close this in a bit since it is apparently fixed.

**Comment by raoulvdberge** [comment]
It's "fixed" because chisel n bits added a workaround, I believe.

**Comment by brisingraerowing** [comment]
Haven't done much testing with the new MCMP release yet. I've mostly been working on a 1.12.2 skyblock pack based on Project Ozone Lite (and trying to find a seed I like for my main world. I usually end up on an island in the middle of nowhere or in a desert).

**Comment by dblsaiko** [comment]
I guess I'm going to close this then.
